#!groovy

// Generated by IBM TransformationAdvisor
// Mon Mar 25 17:01:06 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}